### ISSUE TITLE
Report List error in RDL upload

### ISSUE THREAD

**Issue by mozartapang** [aduguid/SqlServerReportingServices#6]
Error when uploading the rdl file for "Report List" to report manager.

An unexpected error occurred while compiling expressions. Native compiler return value: ‘[BC30179] class 'Textbox16_TextBoxExprHost' and class 'textbox16_TextBoxExprHost' conflict in class 'ReportExprHostImpl'.’.

**Comment by aduguid** [comment]
I'd check the render of the report in Visual Studio or Report Builder before deploying it to your environment. You may need to update the data source.  I also have updated the report since your posting so that may have resolved this issue. I preformed the steps of downloading the file and uploading it into my test environment without any issue.

https://www.microsoft.com/en-us/download/details.aspx?id=53613
https://visualstudio.microsoft.com/vs/
